### ISSUE TITLE
[BUG]cannot install mov-cli

### ISSUE THREAD

**Issue by brianSalk** [mov-cli/mov-cli#128]
**Describe the bug**
`pip install mov-cli` not working

**Expected behavior**
I was expecting the installer to run to completion

**Error**
Collecting mov-cli
  Using cached mov-cli-1.2.5.tar.gz (43 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-jgc385wz/mov-cli_b5861115128440feaf883534944c21ef/setup.py", line 3, in <module>
          from mov_cli.__version__ import __core__ as ver
        File "/tmp/pip-install-jgc385wz/mov-cli_b5861115128440feaf883534944c21ef/mov_cli/__init__.py", line 1, in <module>
          from . import __main__
        File "/tmp/pip-install-jgc385wz/mov-cli_b5861115128440feaf883534944c21ef/mov_cli/__main__.py", line 10, in <module>
          from .websites.actvid import Actvid
        File "/tmp/pip-install-jgc385wz/mov-cli_b5861115128440feaf883534944c21ef/mov_cli/websites/actvid.py", line 6, in <module>
          from Crypto.Cipher import AES
      ModuleNotFoundError: No module named 'Crypto'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Desktop (please complete the following information):**
 - OS: Pop!_Os
 - Version: 22.04
 - pip version: 22.2.2

**Possible cause**
the error message says `no module named Crypto`, but I already installed this module and re-ran `pip install mov-cli` and it still didn't work

**Comment by Poseidon444** [comment]
Try pip install pycryptodomex

**Comment by brianSalk** [comment]
I installed pycryptodomex successfully, how does this help me?  I am still getting the same error when I try to install mov-cli.

**Comment by brianSalk** [comment]
I just got it working, for me the solution was:
`pip install pycryptodome` # as opposed to pycryptodomex
then run
`pip install mov-cli`
Thanks Poseidon444 for pointing me in the right direction
