### ISSUE TITLE
fzf error

### ISSUE THREAD

**Issue by hamzah-sajid-code** [mov-cli/mov-cli#153]
**Before asking**
Check through [Issues](https://github.com/mov-cli/mov-cli/issues) and closed ones too if your question was already answered.

**Question**
Enter your Question under here:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\mov-cli.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\mov_cli\__main__.py", line 56, in movcli
    provider = ask()
  File "C:\Program Files\Python310\lib\site-packages\mov_cli\utils\provider.py", line 48, in ask
    init = fzf_prompt(preselction)
  File "C:\Program Files\Python310\lib\site-packages\fzf\process.py", line 123, in fzf_prompt
    with Fzf.load_with_options(
  File "C:\Program Files\Python310\lib\site-packages\fzf\process.py", line 46, in load_with_options
    return cls(
  File "C:\Program Files\Python310\lib\site-packages\fzf\process.py", line 30, in __init__
    raise RuntimeError(
RuntimeError: fzf was not found in PATH. Please ensure that the process can access fzf.

**Comment by ananasmoe** [comment]
You need to install fzf.
