### ISSUE TITLE
[BUG] Can't watch anything

### ISSUE THREAD

**Issue by shinysocks** [mov-cli/mov-cli#176]
**Describe the bug**
Every single search returns the same error and no media

**Expected behavior**
expected media should play

**Error**
`[!] An Exception has occurred | list index out of range`

**Here's a better error message**
`Traceback (most recent call last):
  File "/home/shinysocks/.local/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
  File "/home/shinysocks/.local/lib/python3.10/site-packages/mov_cli/__main__.py", line 20, in movcli
    provider.redo(CMD_ARGS.s)
  File "/home/shinysocks/.local/lib/python3.10/site-packages/mov_cli/utils/scraper.py", line 214, in redo
    return self.display(search, result)
  File "/home/shinysocks/.local/lib/python3.10/site-packages/mov_cli/utils/scraper.py", line 203, in display
    self.TV_PandDP(mov_or_tv, "p")
  File "/home/shinysocks/.local/lib/python3.10/site-packages/mov_cli/websites/cartoons/kisscartoon.py", line 87, in TV_PandDP
    url, ref = self.cdn_url(link)
  File "/home/shinysocks/.local/lib/python3.10/site-packages/mov_cli/websites/cartoons/kisscartoon.py", line 70, in cdn_url
    hls = re.findall("\\\/cdn\\\/hls\\\/([a-fA-F\d]*)\\\/master\.txt", inter_2)[0]
IndexError: list index out of range`

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: 1.5.1 installed through pip

**Comment by shinysocks** [comment]
how do I support this project btw? ya'll awesome

**Comment by MrLDasVino** [comment]
Its working for me, I have however had similar issues before usually a reinstall fixes it

**Comment by MrLDasVino** [comment]
Well now it has also broken for me, something must have changed again for English providers

**Comment by shinysocks** [comment]
Reinstalling, including old versions, didn't solve the issue for me

**Comment by Poseidon444** [comment]
Guys, I'll try fixing it on Sunday

**Comment by ananasmoe** [comment]
should be fixed
