### ISSUE TITLE
`SIGILL: illegal instruction` error when a provider menu is selected

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#178]
**Describe the bug**
When try to enter the `Indian Providers` in Providers menu, the following error displayed.
#### Steps:
1. enter `mov-cli` in iSH
2. select `Indian Providers` and click enter
3. the following error appeared.

**Expected behavior**
As expected to run smoothly.

**Error**
```
SIGILL: illegal instruction
PC=0x56c007e0 m=3 sigcode=128
instruction bytes: 0xf0 0x70 0xc6 0xe7 0xf0 0x6c 0xc8 0xe7 0x90 0x74 0xc6 0xe7 0x90 0x74 0xc6 0xe7

goroutine 0 [idle]:
runtime: unknown pc 0x56c007e0
stack: frame={sp:0xe7c86c70, fp:0x0} stack=[0x56c02000,0x56c0a000)

runtime: unknown pc 0x56c007e0
stack: frame={sp:0xe7c86c70, fp:0x0} stack=[0x56c02000,0x56c0a000)


goroutine 1 [runnable, locked to thread]:
runtime.gopark(0x5670d3b0, 0x56c4a030, 0x170e, 0x2)
        /usr/lib/go/src/runtime/proc.go:336 +0xf7
runtime.chanrecv(0x56c4a000, 0x0, 0x56c00001, 0x5659ad7b)
        /usr/lib/go/src/runtime/chan.go:576 +0x291
runtime.chanrecv1(0x56c4a000, 0x0)
        /usr/lib/go/src/runtime/chan.go:439 +0x1c
runtime.gcenable()
        /usr/lib/go/src/runtime/mgc.go:219 +0x8f
runtime.main()
        /usr/lib/go/src/runtime/proc.go:184 +0x1d8
runtime.goexit()
        /usr/lib/go/src/runtime/asm_386.s:1315 +0x1

eax    0x0
ebx    0x567c3630
ecx    0x81
edx    0x1
edi    0x0
esi    0x0
ebp    0x0
esp    0xe7c86c70
eip    0x56c007e0
eflags 0x286
cs     0x0
fs     0x0
gs     0x0
Traceback (most recent call last):
  File "/usr/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
  File "/usr/lib/python3.9/site-packages/mov_cli/__main__.py", line 12, in movcli
    cl, url = ask(CMD_ARGS.p)
  File "/usr/lib/python3.9/site-packages/mov_cli/utils/select.py", line 150, in ask
    cl = export(choice, typ, version)
  File "/usr/lib/python3.9/site-packages/mov_cli/utils/select.py", line 86, in export
    return import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mov_cli.websites.indian.None'
```

**Desktop (please complete the following information):**
 - OS: iOS 15.7.8
 - Version: 1.5.2

**Comment by ananasmoe** [comment]
I cannot recreate this problem.
