### ISSUE TITLE
`yoturkish` provider can't able to play

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#183]
**Describe the bug**
I can search a title and select the respective season and episodes, but the video content can't be able to play.

**Expected behavior**
to run the content as expected.

**Error**
```
https://www1.yoturkish.com/gencligim-eyvah-episode-1/
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Scripts\mov-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\__main__.py", line 14, in movcli
    provider.redo(CMD_ARGS.s)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\utils\scraper.py", line 214, in redo
    return self.display(search, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\utils\scraper.py", line 203, in display
    self.TV_PandDP(mov_or_tv, "p")
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\websites\turkish\yoturkish.py", line 72, in TV_PandDP
    url, episode, ref = self.ask(t[self.url])
                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\websites\turkish\yoturkish.py", line 48, in ask
    url, tukibase = self.tuki(req)
                    ^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\utils\scraper.py", line 208, in tuki
    return tukipasti(html)
           ^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\extractors\tukipasti.py", line 7, in tukipasti
    s = re.findall(regex, html)[0]
        ~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 1.5.3

**Comment by ananasmoe** [comment]
Fixed
