### ISSUE TITLE
support for a-Shell

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#189]
**Describe the feature/change you'd like**
I just tried installing the `a-Shell` which is similar to iSH but with lot more packages and features, which is also a lot more faster than iSH in terms of output execution.

**_mov-cli can be installed because it's python but it doesn't able to run.
initially, i think there seems to be issue with locating the local directory._**

**Additional context**
https://holzschu.github.io/a-Shell_iOS/

**Error when launching mov-cli**
```
[Documents]$ mov-cli
/Users/mobile/Library/Application Support/mov-cli
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Application/678DFDE5-993E-4598-8EA7-6B39767C1F61/Library/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
             ^^^^^^^^
  File "/var/mobile/Containers/Data/Application/678DFDE5-993E-4598-8EA7-6B39767C1F61/Library/lib/python3.11/site-packages/mov_cli/__main__.py", line 19, in movcli
    cl, url = ask(p)

              ^^^^^^
  File "/var/mobile/Containers/Data/Application/678DFDE5-993E-4598-8EA7-6B39767C1F61/Library/lib/python3.11/site-packages/mov_cli/utils/select.py", line 117, in ask
    calls = p()
            ^^^
  File "/var/mobile/Containers/Data/Application/678DFDE5-993E-4598-8EA7-6B39767C1F61/Library/lib/python3.11/site-packages/mov_cli/utils/select.py", line 90, in p
    firstStart()
  File "/var/mobile/Containers/Data/Application/678DFDE5-993E-4598-8EA7-6B39767C1F61/Library/lib/python3.11/site-packages/mov_cli/utils/props.py", line 23, in firstStart
    mkdir(home())
FileNotFoundError: [Errno 2] No such file or directory: '/Users/mobile/Library/Application
 Support/mov-cli'
```

**Comment by ananasmoe** [comment]
a-Shell doesn't have a package manager, fzf will not work on a-Shell.

**Comment by bachig26** [comment]
> a-Shell doesn't have a package manager, fzf will not work on a-Shell.

oh okay, i didn't know that...
