### ISSUE TITLE
MacOS, TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by koensa1** [mov-cli/mov-cli#193]
My friend receives an error msg when trying to compile mov-cli from his macbook.
All dependencies, fzf, iina, ffmpeg are installed. 

Stacktrace:
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/utils/lang.py", line 26, in getlang
    with open(f"{home()}/lang.mov-cli", "r") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/danilburov/Library/Application Support/mov-cli/lang.mov-cli'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
             ^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/main.py", line 20, in movcli
    provider: WebScraper = cl.Provider(url)
                           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/websites/english/sflix.py", line 9, in init
    super().init(base_url)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 23, in init
    super().init(base_url)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 23, in init
    self.translated = getlang()
                      ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/utils/lang.py", line 37, in getlang
    localLang = locale.getdefaultlocale()[0][:2]
                ~~~~~~~~^^^^
TypeError: 'NoneType' object is not subscriptable
```

Remark: Creating the lang.mov-cli file in the config directory results in a different error msg:
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
             ^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/main.py", line 20, in movcli
    provider: WebScraper = cl.Provider(url)
                           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/websites/english/remotestream.py", line 9, in init
    super().init(base_url)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 23, in init
    self.translated = getlang()
                      ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/utils/lang.py", line 28, in getlang
    existing(lang)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mov_cli/utils/lang.py", line 20, in existing
    raise LanguageNotAOption(language)
mov_cli.utils.props.LanguageNotAOption: This language '1. en
' is not available Option in the Language's tab. 
Please delete lang.mov-cli in /Users/danilburov/Library/Application Support/mov-cli
```

Remark: The en languagepack is in the lang/ directory 

The version of mov-cli is compiled on the latest version.

**Comment by ananasmoe** [comment]
V3 has been discontinued in favor of V4 and as this issue is related to V3 this issue will be closed.
