### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dennissherb** [mov-cli/mov-cli#201]
Trying to watch anything with any provider, this happens

**Error**
```
Traceback (most recent call last):
  File "/home/userman/.local/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
             ^^^^^^^^
  File "/home/userman/.local/lib/python3.11/site-packages/mov_cli/__main__.py", line 21, in movcli
    provider.redo(s)
  File "/home/userman/.local/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 214, in redo
    return self.display(search, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userman/.local/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 205, in display
    self.MOV_PandDP(mov_or_tv, "p")
  File "/home/userman/.local/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 206, in MOV_PandDP
    url = self.cdn_url(iframe_link, iframe_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userman/.local/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 61, in cdn_url
    n = self.decryption(data["sources"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userman/.local/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 138, in decryption
    key, new_string = self.key_extraction(string, self.gh_key())
                                                  ^^^^^^^^^^^^^
  File "/home/userman/.local/lib/python3.11/site-packages/mov_cli/websites/english/solar.py", line 37, in gh_key
    response_key = self.client.get('https://github.com/enimax-anime/key/blob/e4/key.txt').json()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userman/.local/lib/python3.11/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 7 column 1 (char 6)
```

Fedora 38

**Comment by EbanNox** [comment]
Alredy mentioned here
https://github.com/mov-cli/mov-cli/issues/199

**Comment by ananasmoe** [comment]
#199
