### ISSUE TITLE
[BUG] Asian Provider Problem on Windows

### ISSUE THREAD

**Issue by viadc** [mov-cli/mov-cli#216]
**Describe the bug**
A clear and concise description of what the bug is. Explain the steps that you took leading up to the bug to help aid in recreating it.

**Expected behavior**
When I try to run it I need to go to my script folder and run it as administrator, when I put I want to run asian providers and i for some reason is not running , the same with other providers

**Screenshots**
<img width="960" alt="image" src="https://github.com/mov-cli/mov-cli/assets/93680843/6d4eb201-b209-4465-bc1d-078c7c5d6aac">

**Error**
* https://viewasian.co/watch/marry-my-husband/watching.html?ep=1
https://dood.wf/e/pxtt7bez2qo5
pxtt7bez2qo5
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\mov_cli\extractors\doodstream.py", line 18, in dood
    pass_md5 = re.search(r"/pass_md5/[^']*", webpage_html).group()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Roaming\Python\Python311\Scripts\mov-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\mov_cli\__main__.py", line 21, in movcli
    provider.redo(s)
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\mov_cli\utils\scraper.py", line 214, in redo
    return self.display(search, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\mov_cli\utils\scraper.py", line 203, in display
    self.TV_PandDP(mov_or_tv, "p")
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\mov_cli\websites\asian\viewasian.py", line 83, in TV_PandDP
    url, episode = self.ask(t[self.url])
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\mov_cli\websites\asian\viewasian.py", line 37, in ask
    li = self.doodstream(dood)
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\mov_cli\utils\scraper.py", line 211, in doodstream
    return dood(url)
           ^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\mov_cli\extractors\doodstream.py", line 20, in dood
    raise SelectedNotAvailable
mov_cli.utils.props.SelectedNotAvailable: Not available or it was removed

[!] What would you like to watch: Extraordinary Attorney Woo
https://watchasian.mx/search?type=movies&keyword=Extraordinary+Attorney+Woo
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\adann\AppData\Roaming\Python\Python311\Scripts\mov-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\adann\AppData\Roaming\Python\Python311\site-packages\mov_cli\__main__.py", line 21, in movcli
    provider.redo(s)
  File "C:\Users\adann\AppData\Roaming\Python\Python311\site-packages\mov_cli\utils\scraper.py", line 214, in redo
    return self.display(search, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adann\AppData\Roaming\Python\Python311\site-packages\mov_cli\utils\scraper.py", line 125, in display
    result = self.SandR(q)
             ^^^^^^^^^^^^^
  File "C:\Users\adann\AppData\Roaming\Python\Python311\site-packages\mov_cli\utils\scraper.py", line 122, in SandR
    return self.results(self.search(q))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\adann\AppData\Roaming\Python\Python311\site-packages\mov_cli\websites\asian\watchasian.py", line 18, in results
    ul = soup.find("ul", {"class": "switch-block list-episode-item"}).findAll("li")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'findAll'

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version: [22H2]

**Additional context**

**Possible cause**
If you have a hunch on what might be causing this, please add it here.

**Possible solution**
If you know a way we could fix this, please add it here.

**Version**
If you don't use the latest Version and create a Bug-Report, it will be closed and left unanswered.

**Comment by 4cecoder** [comment]
had anyone been able to replicate this issue?

**Comment by THEGOLDENPRO** [comment]
v3 is no longer being maintained. If you want something I would recommend trying out v4's development build as that is in a better state. https://github.com/mov-cli/mov-cli/issues/188#issuecomment-1981831492
