### ISSUE TITLE
[BUG] movie search actvid provider crypto padding

### ISSUE THREAD

**Issue by Marcus-Arcadius** [mov-cli/mov-cli#227]
Cannot run mov-cli it keeps running into this error whenever I select a movie

Error:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
             ^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/__main__.py", line 21, in movcli
    provider.redo(s)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 214, in redo
    return self.display(search, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 205, in display
    self.MOV_PandDP(mov_or_tv, "p")
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 210, in MOV_PandDP
    url = self.cdn_url(iframe_link, iframe_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 61, in cdn_url
    n = self.decryption(data["sources"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 146, in decryption
    main_decryption = self.aes_decrypt(decryption_key, new_string)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 133, in aes_decrypt
    decrypted_data = unpad(
                     ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/Crypto/Util/Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.

Desktop (please complete the following information):

OS: Android

Version: 14

Version
mov-cli 1.5.7
pip 23.3.2
mpv-android 2023-11-30-release
lxml 5.1.0
ffmpeg 6.1

**Comment by 4cecoder** [comment]
Hi @Marcus-Arcadius,

Thank you for reporting this bug.

I hope you don't mind if i collect some more information about this bug so i can triage it.

What movie title?

What provider/website do you select to watch movies?

**Comment by Reaper176** [comment]
@4cecoder I have this same issue. Any movie title presents the same error under: 
English Providers -> sflix
English Providers -> solar
English Providers -> dopebox

This issue does not appear to be present under:
English Providers -> remotestream
Altho I will not that upon trying to advance the video past its initial buffer will result in the same error.

```
[!] What would you like to watch: silance of the lambs
https://sflix.se/search/silance-of-the-lambs
https://sflix.se/ajax/movie/episodes/8603
https://sflix.se/ajax/sources/5308291
https://rabbitstream.net/embed-4/4l8sHuSUgLAP?z=
https://rabbitstream.net/ajax/embed-4/getSources?id=4l8sHuSUgLAP
https://github.com/theonlymo/keys/blob/e4/key
Traceback (most recent call last):
  File "/home/john/.local/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
             ^^^^^^^^
  File "/home/john/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/mov_cli/__main__.py", line 21, in movcli
    provider.redo(s)
  File "/home/john/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 214, in redo
    return self.display(search, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 205, in display
    self.MOV_PandDP(mov_or_tv, "p")
  File "/home/john/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 210, in MOV_PandDP
    url = self.cdn_url(iframe_link, iframe_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 61, in cdn_url
    n = self.decryption(data["sources"])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 146, in decryption
    main_decryption = self.aes_decrypt(decryption_key, new_string)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/mov_cli/websites/english/actvid.py", line 133, in aes_decrypt
    decrypted_data = unpad(
                     ^^^^^^
  File "/home/john/.local/pipx/venvs/mov-cli/lib/python3.11/site-packages/Crypto/Util/Padding.py", line 95, in unpad
    raise ValueError("PKCS#7 padding is incorrect.")
ValueError: PKCS#7 padding is incorrect.
```
OS: Garuda Linux x86_64
Kernel: 6.7.4-zen1-1-zen
DE: KDE Plasma 5.27.10
Terminal: konsole 23.8.4
Shell: fish 3.7.0
WM: KWin (X11)

mov-cli version: 1.5.7 latest

I am available all day so please feel free to ask for any other details you might need. 

Thank you for your time.

**Comment by EbanNox** [comment]
I have same issues... all of the provider I select spits out that padding error... no mater what... my gues is that thebdecryption key used to decrypt something is eather the sourse of the problem or it is a problem somwhere around that

**Comment by EbanNox** [comment]
I'm posting a question about this and it's related problems we are all experiencing with v3 here -> https://github.com/mov-cli/mov-cli/issues/231

**Comment by ananasmoe** [comment]
V3 has been discontinued in favor of V4 and as this issue is related to V3 this issue will be closed.
