### ISSUE TITLE
[BUG] Big error when selecting any movie or series

### ISSUE THREAD

**Issue by CrimsonKiss** [mov-cli/mov-cli#228]
**Describe the bug**
This error appears every time, no matter what movie I choose nor what provider

**Error**
mov-cli                                                                                                ─╯
/home/crimson_kiss/.config/mov-cli
[!] What would you like to watch: rick and morty
None/ptb-search/?f=search_movies&ptb-search=1&title=rick+and+morty
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 231, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 215, in handle_request
    raise UnsupportedProtocol(
httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
             ^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mov_cli/__main__.py", line 23, in movcli
    provider.redo(s)
  File "/usr/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 214, in redo
    return self.display(search, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 125, in display
    result = self.SandR(q)
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mov_cli/utils/scraper.py", line 122, in SandR
    return self.results(self.search(q))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mov_cli/websites/international/wlext.py", line 17, in results
    m = self.client.get(
        ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mov_cli/utils/httpclient.py", line 22, in get
    req = self.session.get(page, follow_redirects=redirects)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 1055, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 828, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 915, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_client.py", line 1016, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 230, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

**Desktop (please complete the following information):**
 - OS: Arch

**Comment by EbanNox** [comment]
The error vrues for me depending on what provider I chose..  by ue same here.. all providers are scuffed now, while the error output can complain about various different things depending on what provider I chose.  Most of the time tho it complains about a "padding"

**Comment by girvindillon** [comment]
I concur, similar issues occur for everything with me. Not sure what's causing it. I could definitely have installed it incorrectly, since the installation instructions for linux are not very good, and the windows instructions work, but then don't tell you how to run it.

**Comment by EbanNox** [comment]
> I concur, similar issues occur for everything with me. Not sure what's causing it. I could definitely have installed it incorrectly, since the installation instructions for linux are not very good, and the windows instructions work, but then don't tell you how to run it.

The cause is a un mentained or un updated encryption keys for dokicloud fetch. Causing mov-cli to be unable to fetch or stream anything... my gues is that itnwiöö no longer be maintained until v4 comes out...

Posting a question about it that relates to youre issues here -> https://github.com/mov-cli/mov-cli/issues/231

**Comment by EbanNox** [comment]
https://github.com/mov-cli/mov-cli/issues/231

**Comment by THEGOLDENPRO** [comment]
v3 is no longer being maintained. If you want something I would recommend trying out v4's development build as that is in a better state. https://github.com/mov-cli/mov-cli/issues/188#issuecomment-1981831492
