### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by R41DAJ** [mov-cli/mov-cli#233]
**Describe the bug**
I get the same error every time that i try to watch something no matter what

**Error**
!] What would you like to watch: house
https://sflix.se/search/house
https://sflix.se/ajax/v2/tv/seasons/39423
https://sflix.se/ajax/v2/season/episodes/1032
https://sflix.se/ajax/v2/episode/servers/20271/#servers-list
https://sflix.se/ajax/sources/4882642
https://rabbitstream.net/v2/embed-4/CQVJkOsGeAFf?z=
https://rabbitstream.net/v2/ajax/embed-4/getSources?id=CQVJkOsGeAFf
Traceback (most recent call last):
  File "/home/mjinete/.local/bin/mov-cli", line 8, in <module>
    sys.exit(movcli())
             ^^^^^^^^
  File "/home/mjinete/.local/lib/python3.12/site-packages/mov_cli/__main__.py", line 21, in movcli
    provider.redo(s)
  File "/home/mjinete/.local/lib/python3.12/site-packages/mov_cli/utils/scraper.py", line 214, in redo
    return self.display(search, result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mjinete/.local/lib/python3.12/site-packages/mov_cli/utils/scraper.py", line 203, in display
    self.TV_PandDP(mov_or_tv, "p")
  File "/home/mjinete/.local/lib/python3.12/site-packages/mov_cli/websites/english/actvid.py", line 199, in TV_PandDP
    url = self.cdn_url(iframe_link, iframe_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mjinete/.local/lib/python3.12/site-packages/mov_cli/websites/english/actvid.py", line 60, in cdn_url
    data = self.client.get(f"{final_link}getSources?id={rabb_id}").json()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mjinete/.local/lib/python3.12/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Desktop (please complete the following information):**
 - OS: Fedora desktop 39
 -  - Version: 1.5.7

**Comment by ugaugabuga** [comment]
Facing similar issue on Arch and Windows. All four English providers are affected.

**Comment by morris2spears** [comment]
Same here

> Facing similar issue on Arch and Windows. All four English providers are affected.

**Comment by ghost** [comment]
I am facing the same issue with windows 10, using the terminal program and powershell/cmd while trying to watch robocop 2

**Comment by THEGOLDENPRO** [comment]
@r3tr0ananas (or any other v3 devs) could you maybe look into this.

**Comment by THEGOLDENPRO** [comment]
https://github.com/mov-cli/mov-cli/issues/188#issuecomment-1981831492

**Comment by ananasmoe** [comment]
> @r3tr0ananas (or any other v3 devs) could you maybe look into this.

So i have checked and it looks like they have added some url parameters to the getSources link. I can't find the parameters in any request, so this maybe it for all providers that use rabbitstream.

**Comment by THEGOLDENPRO** [comment]
v3 is no longer being maintained. If you want something I would recommend trying out v4's development build as that is in a better state. https://github.com/mov-cli/mov-cli/issues/188#issuecomment-1981831492
