### ISSUE TITLE
[BUG] unable to use movcli with mobile data in Turmux work only on wifi

### ISSUE THREAD

**Issue by Jagadishwar49** [mov-cli/mov-cli#310]
**Describe the bug:**
When ever I search with mobile data nothing is loading but on wifi I'm able to use mov-cli -s films Harry Potter 

**Expected behavior:**
Both in WiFi and mobile data movcli should work 

**Steps to reproduce:**
1. Open Turmux 
2. Turn off WiFi and turn on mobile data 
3. Run   mov-cli -s films Harry Potter

**Screenshots:**

**Logs:**
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/data/data/com.termux/files/usr/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mov-cli", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/__main__.py", line 154, in app
    uwu_app()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/core.py", line 661, in main
    return _main(
           ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/__main__.py", line 98, in mov_cli
    choice = search(query, auto_select, chosen_scraper, config.fzf_enabled)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/search.py", line 32, in search
    choice = prompt(
             ^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/ui.py", line 76, in prompt
    is_just_one, choices = is_it_just_one_choice(choices)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/ui.py", line 56, in is_it_just_one_choice
    for index, _ in enumerate(choices):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/search.py", line 34, in <genexpr>
    choices = (choice for choice in search_results),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/film_central/vidsrcto/scraper.py", line 37, in search
    for search_result in self.tmdb.search(query, limit):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/utils/scraper/the_movie_db.py", line 45, in search
    movie = self.http_client.get(self.search_url.format("movie", query, self.api_key)).json()["results"]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/http_client.py", line 55, in get
    response = self.__httpx_client.get(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_client.py", line 1054, in get
    return self.request(
           ^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/data/data/com.termux/files/usr/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout: timed out

**Platform:**
Android 13
Turmux 
![Uploading Screenshot_2024-05-25-02-33-21-328_com.termux.jpg…]()

**Comment by THEGOLDENPRO** [comment]
I'm not sure if I'm able to reproduce. I tried with 4G+, it took a little longer to buffer the stream but I was able to stream no problem. My assumption is if it's timing out then it's taking a **really long** time for your mobile data to respond to the requests the plugin is performing.

@r3tr0ananas do you think the timeout we set in the http client has something to do with these time out errors. Like do you think the default timeout would do better? Possibly we can experiment with increasing it worse case scenario. 🤔

**Comment by ananasmoe** [comment]
> @r3tr0ananas do you think the timeout we set in the http client has something to do with these time out errors. Like do you think the default timeout would do better? Possibly we can experiment with increasing it worse case scenario. 🤔

The default timeout is 20 seconds. Currently, we have set it to 15 seconds. Streaming content where a page already takes more than 15 seconds to load wouldn't be a good experience.

**Comment by THEGOLDENPRO** [comment]
Alright fair enough 👍

**Comment by THEGOLDENPRO** [comment]
This means this error is most likely an issue on your end; most likely your mobile data is taking too long to respond to requests.

**Comment by THEGOLDENPRO** [comment]
@r3tr0ananas Maybe in v4.4 we should make http request timeout adjustable in the config

**Comment by ananasmoe** [comment]
> @r3tr0ananas Maybe in v4.4 we should make http request timeout adjustable in the config

sure why not

**Comment by Jagadishwar49** [comment]
https://github.com/mov-cli/mov-cli/assets/73735680/9b86a0db-b2f2-4cb5-bfde-499f06e54e61

Hi team 
I'm able to use other cli project only mov-cli is haveing issue with mobile data is there any settings i need to do?

**Comment by ananasmoe** [comment]
> VID_20240527_221036.mp4
> 
> Hi team I'm able to use other cli project only mov-cli is haveing issue with mobile data is there any settings i need to do?

Maybe your mobile provider is blocking that site?

Try switching DNS.

**Comment by THEGOLDENPRO** [comment]
> > VID_20240527_221036.mp4
> > 
> > Hi team I'm able to use other cli project only mov-cli is haveing issue with mobile data is there any settings i need to do?
> 
> Maybe your mobile provider is blocking that site?
> 
> Try switching DNS.

If it's a time out error then the mobile data is just taking too long. I think all we can do from our side is add the adjustable http timeout config to alpha and ask them to try that out with changed timeouts. I can work on this real quick very soon.

**Comment by Jagadishwar49** [comment]
> > VID_20240527_221036.mp4
> > Hi team I'm able to use other cli project only mov-cli is haveing issue with mobile data is there any settings i need to do?
> 
> Maybe your mobile provider is blocking that site?
> 
> Try switching DNS.

@r3tr0ananas 
Thanks i tried 1.1.1.1 wrap dsn it's opening as expected 
Working now

**Comment by ananasmoe** [comment]
> > > VID_20240527_221036.mp4
> > > Hi team I'm able to use other cli project only mov-cli is haveing issue with mobile data is there any settings i need to do?
> > 
> > 
> > Maybe your mobile provider is blocking that site?
> > Try switching DNS.
> 
> @r3tr0ananas Thanks i tried 1.1.1.1 wrap dsn it's opening as expected Working now



> > > VID_20240527_221036.mp4
> > > Hi team I'm able to use other cli project only mov-cli is haveing issue with mobile data is there any settings i need to do?
> > 
> > 
> > Maybe your mobile provider is blocking that site?
> > Try switching DNS.
> 
> @r3tr0ananas Thanks i tried 1.1.1.1 wrap dsn it's opening as expected Working now



> > > VID_20240527_221036.mp4
> > > Hi team I'm able to use other cli project only mov-cli is haveing issue with mobile data is there any settings i need to do?
> > 
> > 
> > Maybe your mobile provider is blocking that site?
> > Try switching DNS.
> 
> @r3tr0ananas Thanks i tried 1.1.1.1 wrap dsn it's opening as expected Working now

![1232865690059542629(1)](https://github.com/mov-cli/mov-cli/assets/132799819/b63ea237-8f44-4508-9f8e-c99d5d1229d5)
