### ISSUE TITLE
[BUG] getting "Error: 'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by Jagadishwar49** [mov-cli/mov-cli#325]
Error: 'NoneType' object has no attribute 'group'
When ever I try to play video in film centeral I'm getting error 
![Screenshot_20240615-122848_Termux](https://github.com/mov-cli/mov-cli/assets/73735680/232063a0-e646-4c0d-b725-f2dd2bad5082)

Full log : 

[CRITICAL] (mov_cli) - An error occurred inside a plugin. This is MOST LIKELY not a mov-cli error, make SURE mov-cli and your plugins are up to date. Also report this to the plugin, not mov-cli!
Error: 'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mov-cli", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/__main__.py", line 154, in app
    uwu_app()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/core.py", line 661, in main
    return _main(
           ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/__main__.py", line 115, in mov_cli
    media = scrape(choice, chosen_episode, chosen_scraper)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/scraper.py", line 29, in scrape
    handle_internal_plugin_error(e)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/plugins.py", line 48, in handle_internal_plugin_error
    raise e
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/mov_cli/cli/scraper.py", line 27, in scrape
    media = scraper.scrape(choice, episode)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/film_central/vidsrcto/scraper.py", line 77, in scrape
    url = vidplay.resolve_source(vidplay_url)[0]
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/film_central/vidsrcto/ext/vidplay.py", line 104, in resolve_source
    futoken = self.get_futoken(key, url, provider_url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/film_central/vidsrcto/ext/vidplay.py", line 82, in get_futoken
    fu_key = re.search(r"var\s+k\s*=\s*'([^']+)'", req.text).group(1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

OS :  ANDROID 14

**Comment by Jagadishwar49** [comment]
Config 

![Uploading Screenshot_20240615-131201_Termux.png…]()

**Comment by Jagadishwar49** [comment]
![Screenshot_20240615-131201_Termux](https://github.com/mov-cli/mov-cli/assets/73735680/80005b78-9f83-4b87-9885-5665e2afa221)

**Comment by THEGOLDENPRO** [comment]
This seems to be a scraper issue and not a mov-cli bug. We can't do anything about it here, you should forward this issue to the plugin's creators or its github repository.

**Comment by r3tr0ananas** [comment]
![image](https://github.com/mov-cli/mov-cli/assets/132799819/2bbdf045-8531-4893-bced-e81ee0099afe)
