### ISSUE TITLE
[BUG] Preview fails on specific characters.

### ISSUE THREAD

**Issue by Hisiste** [mov-cli/mov-cli#338]
Hi! Hope you're doing well. Firstly I need to say that I enjoy very much your work. This is a cool project and is fun to navigate through the code. Keep it up with the good stuff! :)

**Describe the bug:**

The preview fails whenever the image filename starts with a dash (-) or it contains at least one slash (/). Maybe there are even more problematic characters, but I couldn't find them.

**Expected behavior:**

For the preview to show up.

**Steps to reproduce:**

1. Search for anything on mov-cli. I'm using the default scraper of the [mov-cli-youtube plugin](https://github.com/mov-cli/mov-cli-youtube).
2. If you find an option that starts with a dash or contains a slash, the preview will output an error.

**Screenshots:**

https://github.com/user-attachments/assets/18c7ba82-63c5-4e35-b6d6-2dafb96535f5

https://github.com/user-attachments/assets/96c6c0db-ba7d-4650-91d3-d989747f34cc

**Logs:**

The debug option doesn't have anything interesting:
<details>
<summary>mov-cli --debug</summary>

```python
$ mov-cli --debug -s youtube caravan palace reverse
[DEBUG] (mov_cli) - Config -> {'version': 1, 'debug': True, 'player': 'mpv', 'quality': 'sd', 'skip_update_checker': False, 'hide_ip': True, 'ui': {'preview': True, 'watch_options': True, 'display_quality': False}, 'plugins': {'youtube': 'mov-cli-youtube'}, 'scrapers': {'test': 'test.DEFAULT', 'default': 'youtube'}, 'http': {'timeout': 15}}
[DEBUG] (mov_cli) - Scraper args picked up on --> []
[INFO] (mov_cli) - Using 'youtube.DEFAULT' scraper...
[INFO] (mov_cli) - Searching for 'caravan palace reverse'...
[youtube:search] Extracting URL: ytsearch70:caravan palace reverse

Good Afternoon, adriz.
    It's 05:04 PM on a wonderful Sunday! 

[download] Downloading playlist: caravan palace reverse
[youtube:search] query "caravan palace reverse": Downloading web client config
[youtube:search] query "caravan palace reverse" page 1: Downloading API JSON
[youtube:search] query "caravan palace reverse" page 2: Downloading API JSON
[youtube:search] Playlist caravan palace reverse: Downloading 70 items of 70
[download] Downloading item 1 of 70
[download] Downloading item 2 of 70
[download] Downloading item 3 of 70
[download] Downloading item 4 of 70
[download] Downloading item 5 of 70
[download] Downloading item 6 of 70
[download] Downloading item 7 of 70
[download] Downloading item 8 of 70
[download] Downloading item 9 of 70
[download] Downloading item 10 of 70
[download] Downloading item 11 of 70
[download] Downloading item 12 of 70
[download] Downloading item 13 of 70
[download] Downloading item 14 of 70
[download] Downloading item 15 of 70
[download] Downloading item 16 of 70
[download] Downloading item 17 of 70
[download] Downloading item 18 of 70
[download] Downloading item 19 of 70
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Downloading item 47 of 70
[download] Downloading item 48 of 70
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Video is a YouTube short. Pass '--shorts' to the scraper to scrape for them.
[download] Finished downloading playlist: caravan palace reverse
[DEBUG] (mov_cli) - [Cache] Clearing all cache in file or section...
[ERROR] (mov_cli) - There was no results or you didn't select anything.
```

</details>

So, instead, I'll attach the error message that appears on the preview section:

```python
# Trying to preview `Caravan Palace -  Reverse (Official Audio/Visualizer) ~ CaravanPalace`.
Traceback (most recent call last):
  File "/path/to/venv/bin/mov-cli-dev", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/path/to/venv/lib/python3.12/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/typer/core.py", line 723, in main
    return _main(
           ^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/venv/lib/python3.12/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/mov-cli/mov_cli/dev_cli/preview.py", line 63, in image
    file = image_url_to_file(image_url, id, platform).resolve()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/mov-cli/mov_cli/dev_cli/preview.py", line 105, in image_url_to_file
    with file.open("wb") as f:
         ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/mov-cli-temp/Caravan Palace -  Reverse (Official Audio/Visualizer) ~ CaravanPalace'
```

```python
# Trying to preview `-Caravan Palace- Brotherswing (Sub español) ~ Sofia Edits`
Usage: mov-cli-dev preview image [OPTIONS] ID
Try 'mov-cli-dev preview image --help' for help.
╭─ Error ────────────────────────────────────────
│ No such option: -C
╰────────────────────────────────────────────────
```

**Platform:**

 - OS: Arch Linux ~~(btw)~~
 - Version: Linux 6.9.9-arch1-1

**Additional context / possible cause or solution:**

The solution for the beginning dash problem is rather simple. We need to call the `mov-cli-dev` command with `--` before inputting the image name. That way the image name will no longer be seen as a flag.

```diff
diff --git a/mov_cli/cli/search.py b/mov_cli/cli/search.py
index 5c45e13..61bb1d4 100644
--- a/mov_cli/cli/search.py
+++ b/mov_cli/cli/search.py
@@ -49,7 +49,7 @@ def search(query: str, auto_select: Optional[int], scraper: Scraper, fzf_enabled
             display = lambda x: x.display_name, 
             fzf_enabled = fzf_enabled,
             before_display = cache_image_for_preview(cache),
-            preview = "mov-cli-dev preview image {}" if preview else None
+            preview = "mov-cli-dev preview image -- {}" if preview else None
         )
 
     cache.clear_all_cache()
```

For the slash, a quick solution will be to get rid of all slashes before trying to download the image.

```diff
diff --git a/mov_cli/dev_cli/preview.py b/mov_cli/dev_cli/preview.py
index 51ca6ff..78c0bff 100644
--- a/mov_cli/dev_cli/preview.py
+++ b/mov_cli/dev_cli/preview.py
@@ -75,6 +75,9 @@ def image(id: str):
 
 
 def image_url_to_file(image_url: str, id: str, platform: str) -> Optional[Path]:
+    # Sanitize the id.
+    id = id.replace("/", "")
+
     temp = get_temp_directory(platform)
     file = temp.joinpath(f"{id}")
```

This will work.

But, a better solution will be to completely sanitize the id of the image in the `image_url_to_file` function in the first place. A good sanitation could remove any future previewing images problems with funny filenames. I could recommend something similar to Django's `slugify` function:

https://github.com/django/django/blob/dfd63ff43408e7901cc214b0482a7f844244d439/django/utils/text.py#L452-L469

**Version**

4.4.5

**Checklist**
- [X] I have added logs.
- [X] I have added my platform.
- [X] I have added my version number.
- [X] I am sure that this issue is not related to a plugin.

**Comment by ananasmoe** [comment]
Hey,

This is now fixed.

<img src="https://github.com/mov-cli/mov-cli/assets/132799819/6f5a5083-bb79-4dc7-bc32-8a0fc8ffad23" width="200">

**Comment by Hisiste** [comment]
Hi! :)

Thank you for taking your time in fixing this. I'm sorry for saying this, but the beginning dash still causes problems.

https://github.com/user-attachments/assets/42bbbd8a-8659-4106-a542-d1522acb7014

The `mov-cli-dev preview image` command is called and then inside it the `image_url_to_file` and the `slugify` functions are called. My best bet for solving this is still to add the `--` before the id is given:

```diff
diff --git a/mov_cli/cli/search.py b/mov_cli/cli/search.py
index 5c45e13..61bb1d4 100644
--- a/mov_cli/cli/search.py
+++ b/mov_cli/cli/search.py
@@ -49,7 +49,7 @@ def search(query: str, auto_select: Optional[int], scraper: Scraper, fzf_enabled
             display = lambda x: x.display_name, 
             fzf_enabled = fzf_enabled,
             before_display = cache_image_for_preview(cache),
-            preview = "mov-cli-dev preview image {}" if preview else None
+            preview = "mov-cli-dev preview image -- {}" if preview else None
         )
 
     cache.clear_all_cache()
```

**Comment by ananasmoe** [comment]
> Hi! :)
> 
> Thank you for taking your time in fixing this. I'm sorry for saying this, but the beginning dash still causes problems.
> error_dash_2.mp4
> 
> The `mov-cli-dev preview image` command is called and then inside it the `image_url_to_file` and the `slugify` functions are called. My best bet for solving this is still to add the `--` before the id is given:
> 
> ```diff
> diff --git a/mov_cli/cli/search.py b/mov_cli/cli/search.py
> index 5c45e13..61bb1d4 100644
> --- a/mov_cli/cli/search.py
> +++ b/mov_cli/cli/search.py
> @@ -49,7 +49,7 @@ def search(query: str, auto_select: Optional[int], scraper: Scraper, fzf_enabled
>              display = lambda x: x.display_name, 
>              fzf_enabled = fzf_enabled,
>              before_display = cache_image_for_preview(cache),
> -            preview = "mov-cli-dev preview image {}" if preview else None
> +            preview = "mov-cli-dev preview image -- {}" if preview else None
>          )
>  
>      cache.clear_all_cache()
> ```

Should be really fixed now.

<img src="https://github.com/mov-cli/mov-cli/assets/132799819/6f5a5083-bb79-4dc7-bc32-8a0fc8ffad23" width="200">
