### ISSUE TITLE
[BUG] Scraper args: `IndexError: list index out of range`.

### ISSUE THREAD

**Issue by THEGOLDENPRO** [mov-cli/mov-cli#357]
@r3tr0ananas There's a bug with scraper args in the development version (v4.5).

**Expected behavior:**
I should tell me that there are no scraper arguments close to that.

**Steps to reproduce:**

1. Run mov-cli with a non existent scraper argument like so: `mov-cli -s youtube iron man trailer -- --vo`

**Logs:**

```python
$ mov-cli -s youtube iron man trailer -- --vo

Good Afternoon, goldy.
    It's 02:30 PM on a wonderful Monday! 

Traceback (most recent call last):
  File "/home/goldy/.local/bin/mov-cli", line 8, in <module>
    sys.exit(app())
  File "/home/goldy/Documents/projects/goldy/python/mov-cli/mov_cli/cli/__main__.py", line 166, in app
    uwu_app()
  File "/home/goldy/.local/lib/python3.8/site-packages/typer/main.py", line 326, in __call__
    raise e
  File "/home/goldy/.local/lib/python3.8/site-packages/typer/main.py", line 309, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/goldy/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/goldy/.local/lib/python3.8/site-packages/typer/core.py", line 661, in main
    return _main(
  File "/home/goldy/.local/lib/python3.8/site-packages/typer/core.py", line 193, in _main
    rv = self.invoke(ctx)
  File "/home/goldy/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/goldy/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/goldy/.local/lib/python3.8/site-packages/typer/main.py", line 692, in wrapper
    return callback(**use_params)
  File "/home/goldy/Documents/projects/goldy/python/mov-cli/mov_cli/cli/__main__.py", line 130, in mov_cli
    scrape_options = steal_scraper_args(query, selected_scraper[3])
  File "/home/goldy/Documents/projects/goldy/python/mov-cli/mov_cli/cli/scraper.py", line 204, in steal_scraper_args
    f"Unknown arg found: {arg}. Did you mean: {Colours.GREEN}--{did_you_mean_these[0][0]}{Colours.RESET}"
IndexError: list index out of range
```

**Platform:**

 - OS: Arch Linux
 - Version: 6.10.8-arch1-1

**Additional context / possible cause or solution:**

**Version:**

v4.5alpha1

**Checklist**
- [x] I have added logs.
- [x] I have added my platform.
- [x] I have added my version number.
- [x] I am sure that this issue is not related to a plugin.

**Comment by THEGOLDENPRO** [comment]
Wait why was the plugin hook version bumped? Is there a breaking change?

**Comment by ananasmoe** [comment]
I bumped the version because the scraper args need the „args“ from the plugin hook or else the scraper args won’t work.

**Comment by THEGOLDENPRO** [comment]
This entire CLI codebase needs a rw. 😭
