### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by h435er** [mov-cli/mov-cli#363]
It says to me that my mlv player cant reference. Why?

**Mov-cli version:** latest

**Steps to reproduce:**
Just try to play a movie

**Screenshots:**
![Screenshot_2024-10-10-07-08-04-750_com.termux.jpg](https://github.com/user-attachments/assets/af62f7f0-b8fa-45ca-b843-d65fe2d15f24)

**Logs:**

mov-cli -s films dune --debug
[DEBUG] (mov_cli) - Config -> {'version': 1, 'debug': True, 'player': 'mpv', 'quality': 'auto', 'parser': 'lxml', 'skip_update_checker': False, 'auto_try_next_scraper': True, 'hide_ip': True, 'ui': {'fzf': True, 'limit': 20, 'preview': True, 'watch_options': True, 'display_quality': False}, 'plugins': {'films': 'film-central'}, 'scrapers': {'default': 'films', 'test': 'test.DEFAULT'}, 'http': {'timeout': 15}}

Good Morning, co-worker.
    It's 07:03 AM on a wonderful Thursday!

[DEBUG] (mov_cli) - Scraper args picked up on --> []
[INFO] (mov_cli) - Using 'films.ANDROID.DEFAULT' scraper...
[INFO] (mov_cli) - Searching for 'dune'...
[DEBUG] (mov_cli) - [HTTPClient] GET -> https://vadapav.mov/s/dune
[DEBUG] (mov_cli) - [HTTPClient] GET -> https://vadapav.mov/726a32ab-41ef-4a89-a3e2-fe1ee698ec27/
[DEBUG] (mov_cli) - [HTTPClient] GET -> https://vadapav.mov/c9c8dd1c-a019-4076-8e60-bcc7045c5c48/
[DEBUG] (mov_cli) - [Cache] Clearing all cache in file or section...
[INFO] (mov_cli) - Scraping 'Dune Part Two '...
[DEBUG] (mov_cli) - [HTTPClient] GET -> https://vadapav.mov/a51ace36-6c0b-4da3-adb8-01b7a2ade7b1
[DEBUG] (mov_cli) - [Cache] Setting 'a51ace36-6c0b-4da3-adb8-01b7a2ade7b1' cache...
[INFO] (mov_cli) - Playing 'Dune Part Two ' with MPV...
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mov-cli", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 162, in app
    uwu_app()
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/typer/main.py", line 338, in __call__
    raise e
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/typer/main.py", line 321, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/typer/core.py", line 665, in main
    return _main(
           ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/typer/core.py", line 197, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/typer/main.py", line 703, in wrapper
    return callback(**use_params)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/mov_cli/cli/__main__.py", line 158, in mov_cli
    play(media, metadata, chosen_scraper, chosen_episode, config)
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/mov_cli/cli/play.py", line 56, in play
    popen = chosen_player.play(media)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/mov_cli/players/mpv.py", line 68, in play
    raise ReferrerNotSupportedError(
mov_cli.errors.ReferrerNotSupportedError: The MPV player on Android does not support passing referrers, so this media cannot be played. :(

**Platform:**
Termux

**Checklist**
- [x ] I have added logs.
- [ x] I have added my platform.
- [x ] I have added my version number.
- [ ] I am sure that this issue is not related to a plugin.

**Comment by ananasmoe** [comment]
This is not a bug.

The scraper needs to pass a referrer to the media player to stream the content, but this isn't supported on Android.
