### ISSUE TITLE
[QUESTION] Which `.py` file should I run in order to launch mov-cli

### ISSUE THREAD

**Issue by ghost** [mov-cli/mov-cli#364]
**Question:**
Hi. I am trying to package mov-cli for FreeBSD and I forgot how I was able to run the program before. Which `.py` file should I run in order to launch `mov-cli`? I am not using `pip` to install the program. Thanks in advance.

I am getting the error below although i have installed `pyinquirer`. I am trying with this command:
```
% python3.11 -m mov_cli
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "/usr/local/lib/python3.11/site-packages/mov_cli/__init__.py", line 1, in <module>
    from .cli import *
  File "/usr/local/lib/python3.11/site-packages/mov_cli/cli/__init__.py", line 1, in <module>
    from .ui import *
  File "/usr/local/lib/python3.11/site-packages/mov_cli/cli/ui.py", line 21, in <module>
    import inquirer
ModuleNotFoundError: No module named 'inquirer'
```

**Comment by THEGOLDENPRO** [comment]
I'm not entirely sure how the python environment is handled on FreeBSD but I'm going to assume it's similar to other unix-like operating systems like Linux and MacOS.

Typically on unix-like systems (or maybe just Linux idk) when you install mov-cli via pip it should automatically add a `mov-cli` python executable to path (`~/.local/bin/mov-cli`) that invokes the `app()` function in [`mov_cli/cli/__main__.py`](https://github.com/mov-cli/mov-cli/blob/v4/mov_cli/cli/__main__.py#L160) which then in turn triggers the CLI app.

This is what happens when you do `pip install mov-cli` and pip is what handles all of that after the path to the function is set in pyprojecet.toml: https://github.com/mov-cli/mov-cli/blob/1750d54b905730ca3caf5fefa36be4d08aa0b327/pyproject.toml#L76-L77

Executing the CLI app with ``python -m`` isn't a thing in mov-cli *(yet)* but when I was working on rewriting the CLI app for mov-cli `4.5` I actually added that behavior:

![image](https://github.com/user-attachments/assets/91b5982a-368b-41e2-8e8e-d68d02affb6b)

First command is mov-cli `v4.4` and the second is `v4.5`.

Anyways back on track I'm not entirely sure how packaging works on FreeBSD so I'm not sure what the issue could be. Is it possible you could show us the install script used? We packaged mov-cli for Arch Linux before, there we used `python -m installer` to install mov-cli into the python environment and that did the trick, maybe this is a thing in FreeBSD land too? 

https://github.com/mov-cli/arch-packages/blob/319edabf16807a4e47ff656daaa97ad77567f309/mov-cli/PKGBUILD#L48-L56

**Comment by ghost** [comment]
I realized that `PyInquirer` isn't the one that the `mov-cli` does want. So, I ported `inquirer` and the `python3.11 -m mov_cli` command doesn't give any error anymore. I don't think that's the way we supposed to run it so I do want to see a executable binary produced by the ports.
```
# python3.11 -m mov_cli
/usr/local/bin/python3.11: No module named mov_cli.__main__; 'mov_cli' is a package and cannot be directly executed
```
I tried copying `mov_cli/cli/__main__.py` as executable binary as `mov-cli` to the `/usr/local/bin` but that gives another error.
```
# mov-cli
Traceback (most recent call last):
  File "/usr/local/bin/mov-cli", line 13, in <module>
    from .play import play
ImportError: attempted relative import with no known parent package
```
Am I doing it right? I assume `mov_cli/cli/__main__.py` is the file that runs `mov-cli`.

I don't think the arch-way installation is should be used on FreeBSD. I think in FreeBSD, ports on freebsd should not depend on any "installer".

Thanks for your informative comment.

I attached the port's source.
[py-mov-cli.zip](https://github.com/user-attachments/files/17601631/py-mov-cli.zip)

**Comment by ghost** [comment]
I saw that `mov-cli` has `mov_cli/__main__.py` file in the past, why that got removed? Can I update this file to use it as executable binary that will run `mov-cli`?
https://github.com/mov-cli/mov-cli/blob/e551b75c0d5fec3bd054afd826abe64140b81c47/mov_cli/__main__.py 
Can't we create a `__main__.py` file that will run the program like this below?
```
"""
Main module for spotdl. Exports version and main function.
"""

from spotdl._version import __version__
from spotdl.console import console_entry_point

if __name__ == "__main__":
    console_entry_point()
```

**Comment by THEGOLDENPRO** [comment]
that was a very old version of mov-cli, I wasn't maintainer at that time but besides the point, we can add `__main__.py` back in the stable version if you want.

Just create a `__main__.py` file under the mov_cli/ dir and basically add these following and it should work: https://github.com/mov-cli/mov-cli/blob/1750d54b905730ca3caf5fefa36be4d08aa0b327/mov_cli/cli/__main__.py#L161-L162

A bit busy rn so you can create a pull request for the v4 branch, test it on FreeBSD and I'll merge it later. 👍

**Comment by ghost** [comment]
Thanks but apparently it didn't work. I mostly get `ImportError: attempted relative import with no known parent package`

**Comment by ghost** [comment]
I copied executable `mov-cli` binaries created by `pip` to `/usr/local/bin` and they did work. I think I can use these files as a patch for my port. I don't know how can you put them into project. I think it's better this way.

```
# tail -n +1 files/*
==> files/mov-cli-dev.in <==
#!%%PYTHON_CMD%%
# -*- coding: utf-8 -*-
import re
import sys
from mov_cli.dev_cli.__main__ import app
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(app())

==> files/mov-cli.in <==
#!%%PYTHON_CMD%%
# -*- coding: utf-8 -*-
import re
import sys
from mov_cli.cli.__main__ import app
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(app())
```

**Comment by THEGOLDENPRO** [comment]
I guess you'll just have to hack around for v4.4, this will be fixed (actually it has been fixed) in the new CLI app for v4.5.
