### ISSUE TITLE
"Error while connecting to Discord"

### ISSUE THREAD

**Issue by Brandon-E-Ramirez** [mov-cli/mov-cli#80]
I tried uninstalling mov-cli to reinstall it and try again but my system claims it doesn't exist. Heres what outputs when I type "mov-cli":

[X]: Error while connecting to Discord
Traceback (most recent call last):
  File "/home/yaboi_sakurai/.local/bin/mov-cli", line 5, in <module>
    from mov_cli.__main__ import movcli
  File "/home/yaboi_sakurai/.local/lib/python3.10/site-packages/mov_cli/__init__.py", line 1, in <module>
    from . import __main__
  File "/home/yaboi_sakurai/.local/lib/python3.10/site-packages/mov_cli/__main__.py", line 27, in <module>
    default=f"{config.getprovider()}",
  File "/home/yaboi_sakurai/.local/lib/python3.10/site-packages/mov_cli/utils/config.py", line 45, in getprovider
    if config.providerexists() is True:
  File "/home/yaboi_sakurai/.local/lib/python3.10/site-packages/mov_cli/utils/config.py", line 59, in providerexists
    file = f"{config.winorlinux()}/mov_cli/.provider"
  File "/home/yaboi_sakurai/.local/lib/python3.10/site-packages/mov_cli/utils/config.py", line 15, in winorlinux
    return f"/home/{os.getlogin()}"
OSError: [Errno 6] No such device or address

**Comment by ghost** [comment]
Does this Error still happening with the latest version of mov-cli?

**Comment by bachig26** [comment]
> Does this Error still happening with the latest version of mov-cli?

I'm having this error since the v0.4.9. what is this about?

but I can only see the 1st line and not others.
````
[X]: Error while connecting to Discord
````

**Comment by ghost** [comment]
So you can only this ```[X]: Error while connecting to Discord``` nothing more?

**Comment by bachig26** [comment]
> So you can only this ```[X]: Error while connecting to Discord``` nothing more?

Yes

**Comment by ghost** [comment]
![grafik](https://user-images.githubusercontent.com/83706294/212150071-02592b56-bdbb-428d-8208-c19edfa5c796.png)
On my side it's normal

**Comment by ghost** [comment]
Should work as normal after the removal of Discord RPC
