### ISSUE TITLE
[BUG] mov-cli can't run after 0.6.3 update

### ISSUE THREAD

**Issue by bachig26** [mov-cli/mov-cli#98]
**Describe the bug**
app can't run after the latest update.
https://github.com/mov-cli/mov-cli/blob/2505b20ef103738f5111247302575d797db92913/mov_cli/utils/jsunpack.py#L29

possibly due to the incomplete library in the app related to this file.

**Expected behavior**
Nil

**Screenshots**
Nil

**Error**
````
mov-cli
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Scripts\mov-cli.exe\__main__.py", line 4, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\__init__.py", line 1, in <module>
    from . import __main__
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\__main__.py", line 22, in <module>
    from .websites.kinox import kinox
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\websites\kinox.py", line 6, in <module>
    from ..utils import jsunpack
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\mov_cli\utils\jsunpack.py", line 29, in <module>

    from six import PY2
ModuleNotFoundError: No module named 'six'
````

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
Nil

**Possible cause**
Nil

**Possible solution**
Nil

**Version**
0.6.3

**Comment by Poseidon444** [comment]
try `pip install six`
We've forgotten to add it into the requirements.txt
